# config/environments.yaml

# Default configuration
default:
  api:
    base_url: ${API_BASE_URL:http://localhost:8080/api}
    timeout: 30
    verify_ssl: true
    auth_type: bearer
    retry_attempts: 3
    retry_delay: 1
    headers:
      Accept: application/json
      Content-Type: application/json
      User-Agent: BDD-Test-Framework/1.0

# Development environment
dev:
  api:
    base_url: https://api-dev.example.com/v1
    timeout: 60
    verify_ssl: false
    auth_type: bearer
    api_key: ${DEV_API_KEY}
    headers:
      X-Environment: development

# QA environment
qa:
  api:
    base_url: https://api-qa.example.com/v1
    timeout: 30
    verify_ssl: true
    auth_type: bearer
    api_key: ${QA_API_KEY}
    headers:
      X-Environment: qa
      X-Test-Mode: true

# Staging environment
staging:
  api:
    base_url: https://api-staging.example.com/v1
    timeout: 30
    verify_ssl: true
    auth_type: bearer
    api_key: ${STAGING_API_KEY}
    headers:
      X-Environment: staging

# Production environment (for smoke tests only)
production:
  api:
    base_url: https://api.example.com/v1
    timeout: 20
    verify_ssl: true
    auth_type: bearer
    api_key: ${PROD_API_KEY}
    headers:
      X-Environment: production
      X-Test-Mode: true

# Performance testing configuration
performance:
  api:
    base_url: https://api-perf.example.com/v1
    timeout: 120
    verify_ssl: true
    auth_type: bearer
    api_key: ${PERF_API_KEY}
    concurrent_users: 50
    rate_limit: 1000  # requests per second
    headers:
      X-Environment: performance
      X-Load-Test: true

# Mock server configuration
mock:
  api:
    base_url: http://localhost:4010
    timeout: 10
    verify_ssl: false
    auth_type: none
    headers:
      X-Environment: mock

# GraphQL specific configuration
graphql:
  api:
    base_url: https://api.example.com
    graphql_endpoint: /graphql
    timeout: 60
    verify_ssl: true
    auth_type: bearer
    headers:
      Content-Type: application/json

# Microservices configuration
microservices:
  customer_service:
    base_url: https://customers.example.com/api
    timeout: 30
    auth_type: bearer
  
  order_service:
    base_url: https://orders.example.com/api
    timeout: 30
    auth_type: bearer
  
  payment_service:
    base_url: https://payments.example.com/api
    timeout: 45
    auth_type: oauth2
    oauth2_token_url: https://auth.example.com/oauth/token
  
  notification_service:
    base_url: https://notifications.example.com/api
    timeout: 20
    auth_type: apikey